steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/mechat', '.' ]
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud components install kubectl
    gsutil cp gs://container-kubernetes-key/kubeconfig .
    export KUBECONFIG=kubeconfig
    gcloud container clusters get-credentials mechat --zone asia-northeast1-a
    kubectl set image deployment/frontend mechat-frontend=gcr.io/$PROJECT_ID/mechat:$REVISION_ID
#- name: 'gcr.io/cloud-builders/kubectl'
#  args: ['set', 'image', 'deployment/frontend', 'mechat-frontend=gcr.io/$PROJECT_ID/mechat:$REVISION_ID']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=mechat'