steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/mechat:$REVISION_ID', '.' ]
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'compute', 'instances', 'create', 'image-$REVISION_ID', '--image', 'image-1', '--zone', 'asia-northeast1-a' ]
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'compute', 'ssh', 'image-$REVISION_ID', '--zone', 'asia-northeast1-a' ]
  id: 'fetch-resources'
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'run', '--rm', '-d', '-p', '80:8080', 'gcr.io/$PROJECT_ID/mechat:$REVISION_ID' ]
  waitFor: ['fetch-resources']
#images:
#- 'gcr.io/$PROJECT_ID/mechat:$REVISION_ID'

#--image projects/google-containers/global/images/container-vm-v20140522