steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/mechat', '.' ]
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/frontend', 'mechat-frontend=gcr.io/$PROJECT_ID/mechat:$REVISION_ID']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=mechat'
images:
- 'gcr.io/$PROJECT_ID/mechat'
