steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/mechat:$REVISION_ID', '.' ]
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'compute', 'instances', 'create', 'custom-image1', '--image', 'my-image', '--zone', 'asia-northeast1-a' ]
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'compute', 'ssh', 'custom-image1' ]
images:
- 'gcr.io/$PROJECT_ID/mechat:$REVISION_ID'