steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/mechat', '.' ]
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/frontend', 'frontend=gcr.io/$PROJECT_ID/frontend:$REVISION_ID']
images:
- 'gcr.io/$PROJECT_ID/mechat'