apiVersion: v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: mechat
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/chat-180611/mechat
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 3000