apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  labels:
    app: mechat
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: mechat
    tier: frontend