apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: mechat
        tier: frontend
    spec:
      containers:
      - name: mechat-frontend
        image: gcr.io/chat-180611/mechat:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
